"""empty message

Revision ID: 6d4034710626
Revises: 
Create Date: 2019-03-16 13:05:44.260100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4034710626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('laser_freq', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('bin_length', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('data_num', sa.Integer(), nullable=True),
    sa.Column('ver_start_angle', sa.Float(), nullable=True),
    sa.Column('ver_end_angle', sa.Float(), nullable=True),
    sa.Column('ver_step', sa.Float(), nullable=True),
    sa.Column('hor_start_angle', sa.Float(), nullable=True),
    sa.Column('hor_end_angle', sa.Float(), nullable=True),
    sa.Column('hor_step', sa.Float(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_mode'), 'task', ['mode'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('task_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('ver_angle', sa.Float(), nullable=True),
    sa.Column('hor_angle', sa.Float(), nullable=True),
    sa.Column('raw_A', sa.BLOB(), nullable=True),
    sa.Column('raw_B', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_data_timestamp'), 'task_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_data_timestamp'), table_name='task_data')
    op.drop_table('task_data')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_task_mode'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
